### ISSUE TITLE
Problem with conflicting types. (Non-Unity Project)

### ISSUE THREAD

**Issue by StephenAArredondo** [sschmid/Entitas-CSharp#4]
First of all, I'd like to start off saying I really like this ECS framework you built.
The auto-generator tool got me hooked when I saw it. :+1: 

On to the problem I've been wrestling with back and forth now for 2 days. 

After I've created a couple of components and ran the generator, I'm adding the Generated components into my project. In doing so, when I go to create an Entity or Pool, I get an error of type conflicts due to there being a declaration in the Entitas.dll and the public partial class Entity generated in each component file.

<code>

The type 'Entitas.Matcher' in 'G:\Test\TestProject\Components\Generated\ComponentIds.cs' conflicts with the imported type 'Entitas.Matcher' in 'G:\Test\Entitas\bin\Debug\Entitas.dll'. Using the type defined in 'G:\Test\TestProjectComponents\Generated\ComponentIds.cs'.	G:\Test\TestProject\Components\Generated\TestProject.Components.InputComponentGeneratedExtension.cs	25

</code>

I'm pretty sure I could be doing this all wrong, but it thought I went through the steps as described in the wiki,

Any thoughts?

![image](http://i.imgur.com/peRDhr3.png)

**Comment by StephenAArredondo** [comment]
Screenshot for example.

![image](http://i.imgur.com/peRDhr3.png)

**Comment by sschmid** [comment]
Hey Stephen, I haven't setup up a project to prove and reproduce yet, but my first thought was, it doesn't work because you're not using the Entitas sources, but a dll. Try using the source files, that should fix the conflicting types

**Comment by StephenAArredondo** [comment]
Doing as you suggested, there are no further conflicts, but then I got another problem.

![image](http://i.imgur.com/drgrvNP.png)

I no longer had the ability to call .add($ComponentName) on the entity.

I played around with the namespaces a bit and realized that the Components cannot be declared within a namespace for this to work.

Originally

```javascript
using Entitas;
namespace Components
{
    public class LightComponent : IComponent
    {
        public float Direction;
    }
}
```

Working
```javascript
using Entitas;
public class LightComponent : IComponent
{
    public float Direction;
}
```

With this, I'm good to go!

Thanks again for the help. I'll keep you posted. :+1:

**Comment by sschmid** [comment]
There shouldn't be a problem with namespaces. In my tests it's working fine. If you still have problems, let me know. In the email there was this screenshot attached
![Screenshot](https://cloud.githubusercontent.com/assets/233700/7644666/cc537edc-faa8-11e4-8fb1-c8811cc2c9b7.png)

i saw this
```cs
newEntity.addLight(3)
```
with lowercase a. Maybe that's the problem. It's AddLight with uppercase A

I hope that helps

**Comment by StephenAArredondo** [comment]
I noticed that too after I posted, but after correcting those line it was still not working.

I'll give it a shot at a later time. Working on embedding all of this with C# scripting at the moment. :D

**Comment by sschmid** [comment]
Pool, Entity and Matcher are partial classes. If you use the code generator, which is adding functionality to the Pool, Entity and Matcher, you have to the Entitas sources and not the dll.
Partial classes are a purely language feature. When an assembly is compiled, the files are combined to create the type. It isn't possible to spread the files out into different assemblies.
